
platform_url = 'https://xxx.risksense.com'

api_key=""

client_id=123

connector_name="qualys testing"

reportNamePrefix = "test"

networkId=123

username="{qualysurl}"

password="{qualyspassword}"

connector_url="{qualysurl}"

schedule_enabled=true

schedule_type="DAILY"

hourOfDay=2

dayofmonth="2"

dayofweek="3"

autoUrba=false