
platform_url = 'https://platform-in.risksense.com'                             
#your platform URL
api_key=""                                    
#API key of the user in the platform
client_id=100                                   
#client id
connector_name="burpsuiteconnector"                             
#name of the connector you want to provide
networkId=155162                                   
#network to which you want to ingest the assets
burpsuite_api_key=""                          
#api key of burpsuite
createAssetsIfZeroVulnFoundInFile=true        
#whether to create assets if 0 vuln is there
connector_url=""                              
# url of the connector
schedule_enabled=true                         
#whether to enable schedule
schedule_type="DAILY"                         
#whether daily monthly or weekly
hourOfDay=0                                   
#hour of the day
autoUrba=true                                 
#whether to enable auto urba