[platform]
    "url" = '' # Add the url of the platform
    "api_key" = ''  # Add your API key here.
    "client_id" = '' # Update to include your client ID here.
    "assessment_name" = ''
    "file_name" = ''
