
# Update to reflect the URL you use when logging in to RiskSense
platform_url = 'https://platform.risksense.com'


#  An API key generated for your user. This key will have the
#  same permissions as your user. Instructions for generating
#  an API key are found at:
#  https://help.risksense.com/generating-an-api-token
api_key = ''


#  Specify the name of the saved filter you would like to
#  use to generate the .csv file.
saved_filter_name = 'My Saved Filter'


#  The name of the file you would like the output written to.
csv_output_filename = 'my_csv_report.csv'

#  If you are a single-client user, leave this setting alone.
#  If you are a multiclient user, uncomment the client_id
#  setting below, and specify the # the client ID that you
#  wish to work with.

#client_id = 12345