platform_url = 'https://xxxx.risksense.com'
api_key=''
client_id=123
connector_name=""
authMechanism="APIKey"
networkId=123
username=""
password=""
connector_url=""
schedule_enabled=true
schedule_type="DAILY"
hourOfDay=2
dayofmonth="2"
dayofweek="3"
autoUrba=false


