platform_url = 'https://xxx.risksense.com'
api_key=""
username=''
password=""
client_id=1234
connector_name=""
networkId=0
connector_url=""
schedule_enabled=False
schedule_type=""
hourOfDay=0
dayofmonth="0"
dayofweek="0"
autoUrba=False