platform_url = ''
api_key=""
clientid=''
client_secret=""
client_id=123
connector_name=""
networkId=
connector_url=""
schedule_enabled=true
schedule_type="DAILY"
hourOfDay=11
dayofmonth="2"
dayofweek="3"
autoUrba=true